//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSServer.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSERP.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locale=en-us
        ///
        ///STR_EXCEPTION=An error has occured
        ///STR_EXCEPTION_CRITICAL=A critical error has occurred, so server will terminate.
        ///STR_EXCEPTION_IO_FILE_WRITE=파일을 생성이나 쓰는도중 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_IO_FILE_READ=파일을 읽는중 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_IO_FOLDER_WRITE=폴더를 생성하는동안 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_IO_FOLDER_ACCESS=폴더에 접근하는동안 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_SQL_CONNECTION=DB 서버에 접속하는동안 오류가 발생하였습니다.
        ///STR_EXCEPTION_SQL_QUERY=DB 쿼리를 실행하는동안 오류가 발생하였습니다.
        ///
        ///STR_LOG_ENGINE_INITED=ERP 엔진 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Language_en_us {
            get {
                return ResourceManager.GetString("Language_en_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale=ko-kr
        ///
        ///STR_EXCEPTION=오류가 발생하였습니다.
        ///STR_EXCEPTION_CRITICAL=치명적인 오류가 발생하여 서버가 종료됩니다.
        ///STR_EXCEPTION_IO_FILE_WRITE=파일을 생성이나 쓰는도중 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_IO_FILE_READ=파일을 읽는중 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_IO_FOLDER_WRITE=폴더를 생성하는동안 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_IO_FOLDER_ACCESS=폴더에 접근하는동안 오류가 발생하였습니다. ({0})
        ///STR_EXCEPTION_SQL_CONNECTION=DB 서버에 접속하는동안 오류가 발생하였습니다.
        ///STR_EXCEPTION_SQL_QUERY=DB 쿼리를 실행하는동안 오류가 발생하였습니다.
        ///
        ///STR_LOG_ENGINE_INITED=ERP 엔진 초기화 완료!
        ///STR_LOG_ENGINE_INIT_FAIL=ERP 엔 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Language_ko_kr {
            get {
                return ResourceManager.GetString("Language_ko_kr", resourceCulture);
            }
        }
    }
}
